### ISSUE TITLE
Please explain the expected behavior

### ISSUE THREAD

**Issue by adrienbernede** [vsoch/action-updater#16]
https://github.com/vsoch/action-updater/blob/2c2216e27ee963aaa31ff0ff81de007acb84b9c2/action.yaml#L51

I am not sure to understand this if statement. In fact, I understand the code, but I don’t understand it in regard to the comment above: how is this covering the case where pwd is not provided ?

**Comment by vsoch** [comment]
It’s probably a bad comment. Basically if pwd is provided as a period, I anticipate here the library not properly handling it (so I convert to an actual path). This indeed could be improved upon to just take an abspath in the Python code and allow for “.”

**Comment by adrienbernede** [comment]
Re-reading, I think you meant "if path is provided".

**Comment by vsoch** [comment]
Yes it’s saying “if the present working directory (as a .) is provided for path, make sure we expand that into an actual path.”

**Comment by adrienbernede** [comment]
OK, re-re-reading, and now I get it: for you, pwd means 'path = "."'
For me it meant 'the command pwd'. So per the comment, I was understanding that pwd might not exist on the system, which had nothing to do with the following code of course.
Being better awake now, I get it.
