### ISSUE TITLE
Handling of non-zero return code

### ISSUE THREAD

**Issue by adrienbernede** [vsoch/action-updater#17]
https://github.com/vsoch/action-updater/blob/2c2216e27ee963aaa31ff0ff81de007acb84b9c2/action.yaml#L67

Isn’t a composite action failing on non-zero return codes (meaning the action would not reach the return-code handling section)? I couldn’t confirm with documentation, but in gitlab it’s a typical issue: we need to protect against failures if we want to handle them ourselves:

```
- command-that-my-fail || ( cmd-rt = $? && echo "Caught Failure $cmd-rt")
```

**Comment by adrienbernede** [comment]
Re-reading (again :) ):
Probably fine because of
```
run: |
```

**Comment by vsoch** [comment]
Yes, good call! This would work, or providing an argument to the client to allow failure.

**Comment by vsoch** [comment]
Let’s keep this open to re-address - I think we do want the or statement.
