### ISSUE TITLE
Can we extend to do linting actions too?

### ISSUE THREAD

**Issue by vsoch** [vsoch/action-updater#5]
These would likely need to be a different entrypoint - not update.

**Comment by mikemhenry** [comment]
Personally for this I use https://github.com/panda0603/lint-action not sure if it is worth making a new one or just calling this with subprocess.

**Comment by vsoch** [comment]
Thanks! So I actually added this functionality (and forgot to close the issue!) Here is the PR:
https://github.com/vsoch/action-updater/pull/21/files

Sorry about that and thanks for the pointer!
